# test everything works
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2'
gem 'responders', '~> 2.0'
## Use sqlite3 as the database for Active Record for Windows
# gem 'sqlite3'

# These two mysql gems are for Mysql Active Record for Windows
gem 'activerecord-mysql-adapter', platforms: [:mingw, :mswin]
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

gem 'foundation-rails', '5.3.0.0'

#Fixes for WINDOWS 8

platforms :ruby do # linux
  gem 'unicorn'
end

# platforms :mswin do
	#Version 1.9.1 doesn't play nice with Windows
	gem 'coffee-script-source', '1.8.0'
	# gems specific to windows
# end

# To fix Windows timezone issue
gem 'tzinfo-data', platforms: [:mingw, :mswin]
require 'rbconfig'
gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i


gem 'devise' # user registration handling

gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby' # payments

gem 'font-awesome-sass'
gem 'mail' # emails

gem "brakeman", :require => false # security gem--cool stuff!

gem "paperclip", "~> 3.1" # image and file uploads

gem "geocoder" # ip lookup
gem 'rubyzip' # dependency for geocoder unzipping IP .csv's

gem 'paypal-sdk-rest' # paypal payments to publisher

gem 'htmlbeautifier' # beautifier for formatting 
gem 'rubocop' # ruby code quality

gem 'kaminari' # pagination
gem 'ransack' # search and sort

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.9'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
group :development do
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm'
  gem 'capistrano3-unicorn'
  gem 'capistrano-rails-console'
  gem 'web-console', '~> 2.0' 
end

gem 'sqlite3'

# Use debugger
# gem 'debugger', group: [:development, :test]

# notepad for getting a local db set up:
# $ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
# $ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
# $ wget http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
# $ gunzip GeoIP.dat.gz
# $ gunzip GeoIPASNum.dat.gz
# $ gunzip GeoLiteCity.dat.gz
# $ sudo cp GeoIP.dat GeoIPASNum.dat GeoLiteCity.dat /usr/share/GeoIP/
# $ geoiplookup -f /usr/share/GeoIP/GeoLiteCity.dat 23.66.166.151
# or
# wget https://github.com/fiorix/freegeoip/releases/download/v3.0.4/freegeoip-3.0.4-linux-i386.tar.gz
# tar -zxvf [above file]
